### ISSUE TITLE
The hot reload doesn't work on the npm run dev

### ISSUE THREAD

**Issue by mickydeveloper** [sanity-io/example-frontend-vue-js#1]

**Comment by bjoerge** [comment]
Hi @mickydeveloper. I'm not able to reproduce this. Which platform, node/npm version are you on?

This frontend is basically just the boilerplate from `vue init webpack` and a few views. You could try initializing a new vue project and copy the `src` folder over and see if that helps.

**Comment by mickydeveloper** [comment]
npm 4.1.2
node v7.7.2
Well as far as I could tell the hot reload on boilerplate work with the vue init webpack. I think it might have something to do with webpack-hot-middleware you are using in your dev-server.js

**Comment by bjoerge** [comment]
Thanks!

I can confirm it doesn't work on node v7.7.2. A fresh `vue init webpack` _does_ work.

I'll regenerate the boilerplate and see if that fixes it.

**Comment by bjoerge** [comment]
f156de1 updates the boilerplate according to what `vue init webpack` using the latest vue-cli gives you.

Would you like to pull/re-clone and see if it helps?

**Comment by mickydeveloper** [comment]
Great that fixes it. 
btw. Great work on Sanity enjoy using it.

**Comment by bjoerge** [comment]
Nice!

Thanks for reporting this issue & glad you're enjoying Sanity :)

**Comment by mickydeveloper** [comment]
Hi Bjørge,

I have been running into the issue multiple time now.
When I run sanity start:
Checking configuration files...
Cannot read property 'plugin' of undefined

I have tried updating my node to the newest version.
But only when creating the new Sanity project from existing and cooping the
schema fixes the issue.

Do you have any idea what could be the cause ?

Best Regards,
Mikolaj

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mickydeveloper** [comment]
Sorry for the bother.
Have figured out the issue it was about the local environment, it didn't
work when run from the Atom cmd but system cmd run fixes the Issue.
Have a good day!
